version: 2

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/vscode-js-profile-core"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/vscode-js-profile-flame"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/vscode-js-profile-table"
      schedule:
          interval: "daily"
      versioning-strategy: increase
